name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: php-actions/composer@v6
      - run: npm ci
      - uses: php-actions/phpunit@v3
